---

- name: show version
  hosts: HK-BR
  gather_facts: false
  connection: local
  tasks:
    - name: Show Version HK-BR01
      telnet:
        ignore_errors: yes
        user: ipdc_afiq
        password: ZpSG6VKqJNdFX9Uk
        login_prompt: "login: "
        timeout: 600
        prompts:
          - '[>|#]'
        ios_command:
          commands:
            - terminal length 0
            - show int desc