- name: "Connecting..."
  hosts: switches
  gather_facts: no
  connection: local

  tasks:
    ###
    # Build a Connection
    #
    - name: Doing the Telnet
      telnet:
        user: ipdc_afiq
        password: ZpSG6VKqJNdFX9Uk
        login_prompt: "login: "
        prompts:
          - '[>|#]'

  tasks:
    ###
    # Collect data
    #
    - name: Gather SW Information
      cisco.ios.ios_facts:
      when: ansible_network_os == 'cisco.ios.ios'

    ###
    # Demonstrate variables
    #
    - name: Display SW Information
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"

    - name: Write facts to disk using a template
      copy:
        content: |
          #jinja2: lstrip_blocks: True

          IOS device info:
            {% for host in groups['ios'] %}
            Hostname: {{ hostvars[host].ansible_net_hostname }}
            Version: {{ hostvars[host].ansible_net_version }}
            Model: {{ hostvars[host].ansible_net_model }}
            Serial: {{ hostvars[host].ansible_net_serialnum }}
            {% endfor %}
        dest: /var/log/ansible-logs/hk-sc
      run_once: yes

    ###
    # Get running configuration
    #

    - name: Backup SW
      cisco.ios.ios_config:
        backup: yes
      register: backup_eos_location
      when: ansible_network_os == 'cisco.ios.ios'

    - name: Create backup dir
      file:
        path: "/var/log/ansible-logs/backup/{{ inventory_hostname }}"
        state: directory
        recurse: yes

    - name: Copy Backup File
      copy:
        src: "{{ backup_ios_location.backup_path }}"
        dest: "var/log/ansible-logs/backup/{{ inventory_hostname }}/{{ inventory_hostname }}.bck"
      when: ansible_network_os == 'cisco.ios.ios'