---

- name: show version
  hosts: HK-BR
  gather_facts: false
  connection: local
  tasks:
    - name: Show Version HK-BR01
      telnet:
        user: ipdc_afiq
        password: ZpSG6VKqJNdFX9Uk
        login_prompt: "login: "
        prompts:
          - '[>|#]'
        command:
          - terminal length 0
          - show version
          - show int desc
        register: command_output

    - debug:
       var: command_output.stdout_lines