---

- name: show version
  hosts: HK-ED
  gather_facts: false
  connection: local
  tasks:
    - name: Show Version HK-BR01
      telnet:
        user: ipdc_afiq
        password: CdLGuMK1zPmH7akC
        login_prompt: "Username: "
        prompts:
          - '[>|#]'
        command:
          - terminal length 0
          - show version
          - sh clock          
